# 160302 run: 
../figures/quality_control.160302.pdf: /srv/gsfs0/scratch/nsabell/rpe/counts/set3
	Rscript quality_control.cmdline.R /srv/gsfs0/scratch/nsabell/rpe/counts/set3/ ../figures/quality_control.160302.pdf

# 160223 run: 
../figures/quality_control.160223.pdf: /srv/gsfs0/scratch/nsabell/rpe/counts/set2
	Rscript quality_control.cmdline.R /srv/gsfs0/scratch/nsabell/rpe/counts/set2/ ../figures/quality_control.160223.pdf

# 160202 run:  
../figures/quality_control.160202.pdf: /srv/gsfs0/scratch/nsabell/rpe/counts/set1
	Rscript quality_control.cmdline.R /srv/gsfs0/scratch/nsabell/rpe/counts/set1/ ../figures/quality_control.160202.pdf
