Rscript rpe_specific_genes/rpe_specific_gene.GTExV7.R
Rscript rpe_specific_genes/plot_rpe_specific_gene.GTExV7.R
Rscript rpe_specific_genes/plot_QQplot.R
bash rpe_specific_genes/GSEA.sh
Rscript rpe_specific_genes/make_GSEA_supp_table.R